# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://schorndorfer.github.io/nbdev_test/"

git_url = "https://github.com/schorndorfer/nbdev_test/tree/master/"

def custom_doc_links(name): return None
